spring:
  datasource:
    platform: 
    url:
    username:
    hikari:
      maximum-pool-size:
  jpa:
    show-sql:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        dialect:
        format_sql:
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: http://localhost:3000
  endpoint:
    health:
      show-details: always